name: Connect to remote machine
run-name: Connect
on: workflow_dispatch

jobs:
  Demo-Github-Action:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: ls .

      - name: Ping server
        shell: bash
        run: ping 129.159.154.25
