name: My Gitub action
run-name: A demo
on: workflow_dispatch

jobs:
  Demo-Github-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Check SSH"
      - run: echo "${{ secrets.my_secret }}"
      - run: ls /