name: Connect to remote machine
run-name: Connect
on: workflow_dispatch

jobs:
  Demo-Github-Action:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: ls .
      - shell: bash
        run: ssh -i < (echo $private_key) $username@$public_ip
        env:
          private_key: ${{ secrets.private_key }}
          public_ip: ${{ secrets.public_ip }}
          username: ${{ secrets.username }}
      - shell: bash
        run: ls .
      - shell: bash
        run: "FINISHED"