name: Connect to remote machine
run-name: Connect
on: workflow_dispatch

jobs:
  Demo-Github-Action:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: ls .
      - shell: bash
        run: echo "$private_key" > private_key.key
        env:
          private_key: ${{ secrets.private_key }}
      - shell: bash
        run: chmod 755 private_key.key
      - shell: bash
        run: ls .
      - shell: bash
        run: ssh -i ./private_key.key $username@$public_ip
        env:
          public_ip: ${{ secrets.public_ip }}
          username: ${{ secrets.username }}
      - shell: bash
        run: ls .
      - shell: bash
        run: "FINISHED"