name: My Gitub action
run-name: A demo
on: workflow_dispatch

jobs:
  Demo-Github-Action:
    runs-on: ubuntu-latest
    steps:
      - run: touch log.txt
      - run: ls
      - name: "Work around secrets"
        shell: bash
        run: echo "$super_secret" > log.txt
        with:
          super_secret: ${{ secrets.my_secret }}
      - run: cat log.txt