name: My Gitub action
run-name: A demo
on: workflow_dispatch

jobs:
  Demo-Github-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Check SSH"
      - name: "Work around secrets"
        shell: bash
        run: echo "$super_secret"
        with:
          super_secret: ${{ secrets.my_secret }}
      - run: ls /